# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "Blowfish"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]
# robots = ""

disableImageOptimization = false

# defaultBackgroundImage = "/img/home_background.jpg"
# defaultFeaturedImage = "/img/ocean.jpg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "page" # valid options: page, profile, hero, card, background, custom
  # homepageImage = "/img/forest.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 5
  showMoreLink = false
  # showMoreLinkDest = "posts"
  cardView = false
  cardViewScreenWidth = false
  # layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = true
  showViews = true
  showLikes = true
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = false
  showEdit = false
  # editURL = ""
  # editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 6
  showTaxonomies = true 
  showAuthorsBadges = false 
  showWordCount = false
  # sharingLinks = [ "linkedin", "twitter", "reddit", "whatsapp", "telegram", "pinterest", "facebook", "email"]

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = false
  showViews = true
  showLikes = true
  showTableOfContents = true
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy","term"]

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = true
  showLikes = true
  showTableOfContents = true
  cardView = false

[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = true
  showLikes = true
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  
[firebase]
  apiKey = "AIzaSyB2bYjnknhtJO93mOWz6BoibKtopHBE2Ig"
  authDomain = "gigigatgat-ffb92.firebaseapp.com"
  projectId = "gigigatgat-ffb92"
  storageBucket = "gigigatgat-ffb92.appspot.com"
  messagingSenderId = "861684753486"
  appId = "1:861684753486:web:51fe5e0a9524a867c54f1f"
  measurementId = "G-DVNJ01P5C9"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

#[buymeacoffee]
#  identifier = "nunocoracao"
#  globalWidget = true
#  globalWidgetMessage = ""
#  globalWidgetColor = "#FFDD00"
#  globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
